### ISSUE TITLE
Plugin not showing any references, error in console "pandocMarkdownToHTML not found"

### ISSUE THREAD

**Issue by MSBack** [mgmeyers/obsidian-pandoc-reference-list#38]
I have installed the plugin, but I cannot get it to work. It doesn't show any references ("No citations found in the active document") despite valid references with correct citekeys and the correct bibtex file path in the plugin settings. I am not sure if this is helpful, but I get this error in the Obsidian console:

```
plugin:obsidian-pandoc-reference-list:4638 Error: pandocMarkdownToHTML not found: pandoc
    at eval (plugin:obsidian-pandoc-reference-list:4530:13)
    at Generator.throw (<anonymous>)
    at rejected (plugin:obsidian-pandoc-reference-list:72:29)
```
Some things to note:
- I have pandoc on the System PATH, but the plugin cannot find it, so I supplied the absolute path in the settings.
- The "Open view" command is not visible in my command palette, but I can open it by setting a hotkey.

I tested the plugin in an empty vault, and it did work with the same settings and the same test document, so it seems that the issue is some interaction with another plugin or some settings. However, the "Open view" command is still missing from the command palette is reproducible in the test vault.

**Comment by MSBack** [comment]
Update: I got the plugin to work by disabling all community plugins using the Divide and Conquer plugin, to debug the issue. Strangely, it still works after I re-enabled them **all** again, so I am unsure which interaction or conflict, if any, caused the issue.

**Comment by MSBack** [comment]
Update: After closing and relaunching Obsidian, the reference list once again just says "No citations found in the active document", so the workaround in above did only temporarily solve the issue.

**Comment by mgmeyers** [comment]
Not sure what's going on here @MSBack. That error means that the plugin can't find pandoc on your system. The "Open view" command is only available if the view has been closed for some reason. The sidebar view should open automatically when the plugin loads.

**Comment by thesofakillers** [comment]
I am also facing the issue of no references, despite correct .bib file and pandoc paths configured. I however do not have any errors in my obsidian console.

**Comment by hlageek** [comment]
I experienced the same issue. In my case, it turned out that I had a conflicting older version of `pandoc` installed via `conda`. The issue got resolved after I had removed the `conda` `pandoc` executables which defaulted pandoc to my `brew` installation of `pandoc`.

**Comment by Kullenej** [comment]
I have the same problem. What did you do? Uninstall pandoc completely through the terminal or?

**Comment by JoelMon** [comment]
Same here. I had pandoc 2.9.2.1-3ubuntu2 amd64 installed. Once I upgraded (2.19) the problem was resolved.

I've been waiting for a feature like this FOR A LONG TIME. It was the one thing I missed from Zettlr.

Thanks dev team! :heart:

**Comment by sdrakulich** [comment]
Same issues, am on Windows 10 with one pandoc installation. Pandoc functionality works elsewhere in Obsidian.

The References List Plugin "works" when Obsidian loads, inserting any new citation keys breaks the reference list ("no references in document"). Removing this new citation key (i.e., reverting document to how it was when Obsidian loaded) "fixes" the reference list and shows the citations again. Disabling and reenabling the plugin breaks the previously-working citations.

Note that, "Attempt to find pandoc" fails, and Validate fails with the same error listed in this issue thread. I hope that helps resolve this, really hoping to use this plugin, thank you!

**Comment by MSBack** [comment]
> Not sure what's going on here @MSBack. That error means that the plugin can't find pandoc on your system. The "Open view" command is only available if the view has been closed for some reason. The sidebar view should open automatically when the plugin loads.

This issue is still not resolved for me. I have specified the path to the Pandoc executable, because the plugin is unable to find it on its own. Pandoc is installed in the standard directory for local users (~\AppData\Local\Pandoc\pandoc.exe).

When I try to “Validate Pandoc configuration” without supplying a path, I get the message “path to pandoc is required”. After supplying the path and validating again, I get the message “not found: pandoc”. As mentioned, my path is ~\AppData\Local\Pandoc\pandoc.exe (with the rest indicated by ~ supplied). This is the same path as found using Get-Command Pandoc in PowerShell.

**Comment by MSBack** [comment]
As others have mentioned, Pandoc works fine in the Pandoc Plugin, for example, even without supplying the path to the executable. So for some reason, other plugins can find Pandoc, but this plugin cannot.

I have version 2.19.2 of Pandoc installed, so an outdated version is not the issue.

**Comment by nicolafern** [comment]
I'm having this same issue, where it reports 'pandocMarkdownToHTML path to pandoc is required'.  The plugin can't locate the Pandoc installation, even when given the direct path to it.  I'm running Windows 11, Pandoc 2.19.2 (latest).  I'm using Citations to actually add my references into the document and was really interested in just having the live reference list in the sidebar.

This is a very clean vault, set up today as I'll be using Obsidian to write my thesis and other longform papers and wanted to separate that from my main notes vault as a clean writing space.  If it helps, the community plugins I have activated are: 

- Advanced tables
- Better Word Count
- Citations
- Excalidraw
- Homepage
- Icon Folder
- LanguageTool
- Longform
- Make.md
- Note Refactor
- Obsidian Tabs
- Pandoc Reference List
- Quiet Outline
- Templater
- Word Sprint

**Comment by OliverDudgeon** [comment]
I was having a similar problem to people here where I installed Pandoc the usual way (Windows). But the plugin wasn't able to load Pandoc (even with the _fallback path_ set to `C:\Users\<user>\AppData\Local\Pandoc\pandoc.exe`) and `Get-Command Pandoc` errored. The Pandoc install directory was in my PATH. **Turns out all I had to do was restart the laptop**.

**Comment by MSBack** [comment]
Oh, I have restarted plenty of times, but it hasn't fixed the problem.

**Comment by MSBack** [comment]
Okay, after a lot of debugging, I have finally figured out the issue. For me, the issue is some interference from the Pocket integration plugin [https://github.com/nybbles/obsidian-pocket](https://github.com/nybbles/obsidian-pocket).

So, if you're like me and 1) you have made sure Pandoc is specified in your system PATH, but Pandoc Reference List still cannot find it automatically, nor when you supply the absolute pandoc path in settings and 2) you have the Pocket integration plugin installed and enabled, try disabling it.

I literally have 100 plugins installed (not all enabled) and out of all of those, I only needed to disable Pocket integration, after which Pandoc Reference List was able to find pandoc automatically and display the reference list without issues.

I figured this out in a test vault where I first installed Pandoc Reference List, and it was working fine. Then I added all the others from my real vault one by one, until Pandoc Reference List stopped working. It stopped working after installing and enabling Pocket integration, and worked again after I disabled it.

Then, in my real vault, I just disabled Pocket integration, and now everything works as expected.
